language: java
install: mvn install -Dgpg.skip=true
jdk:
- oraclejdk7
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: EHE0gqqjLcICY7CPynUXGlb/Ig2sGuBpnm32lK/H+vX4vnMaH0w9cktB8xZIV1jkVJ1tJYAojEsNJUNIV2aKcLTVEKdYigpcvJZNg4c9tlK60Khli5hbAEf5CFxBaq7aUySkewQQ2QcAmGjBUle4iLyo+PPXiQKkjtmQUfqDVxM=
